[package]
name = "strava-data"
version = "0.1.1"
authors = ["Saju Thankappan <sajuthankappan@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Strava data api bindings"
homepage = "https://github.com/sajuthankappan/strava-data-rs"
repository = "https://github.com/sajuthankappan/strava-data-rs"
readme = "README.md"
keywords = ["strava"]
categories = ["api-bindings"]

[dependencies]
log = "0.4.8"
serde = { version = "1.0.105", features = ["derive"] }
serde_json = "1.0.48"
surf = "1.0.3"
async-std="1.5.0"
